name: production

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | docker login -u anywaysbot --password-stdin

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag anywaysopen/cityflows-app:prod --tag anywaysopen/cityflows-app:prod-0.$GITHUB_RUN_NUMBER
      
    - name: Publish the image.
      run: docker push anywaysopen/cityflows-app:prod
    - name: Publish the image.
      run: docker push anywaysopen/cityflows-app:prod-0.$GITHUB_RUN_NUMBER

  